services:
  - type: web
    name: cfe-avisos-ciclones
    runtime: python
    buildCommand: pip install -r requirements.txt && cd whatsapp_server && npm install --no-audit
    startCommand: cd whatsapp_server && node server.js & cd /opt/render/project/src && gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        value: 10000
      - key: POLL_INTERVAL_MINUTES
        value: 15
      - key: OPENWA_SERVER_URL
        value: http://localhost:8085
