services:
  - type: web
    name: cfe-avisos-ciclones
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
      - key: POLL_INTERVAL_MINUTES
        value: 15
